<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-JMB9U63" failures="1" tests="5" name="Personal Loan" time="0.057" errors="0" timestamp="2023-01-09T17:40:06 IST">
  <testcase classname="test.Day2" name="ploan" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.Day2.ploan(Day2.java:13)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- ploan -->
  <testcase classname="test.Day1" name="Demo" time="0.013"/>
  <testcase classname="test.Day4" name="LoginAPIHomeLoan" time="0.017"/>
  <testcase classname="test.Day4" name="MobileLoginHomeLoan" time="0.002"/>
  <testcase classname="test.Day4" name="WebloginHomeLoan" time="0.001"/>
  <testcase classname="test.Day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal Loan -->
